--- 
title: "Анализ данных для лингвистов"
author: "Г. А. Мороз"
bibliography:
- bibliography.bib
editor_options:
  chunk_output_type: console
link-citations: yes
documentclass: book
site: bookdown::bookdown_site
biblio-style: apalike
---

# О курсе

Материалы для курса Анализа данных для лингвистов, Школа лингвистики НИУ ВШЭ.

* вместо первой лекции можно посмотреть [запись лекции 2021.01.13](https://youtu.be/HmLcBJnfipk)
* вместо второй лекции можно посмотреть [запись лекции 2021.01.15](https://youtu.be/V_c_K_wBMuY)
* вместо третей лекции можно посмотреть [запись лекции 2021.01.20](https://youtu.be/cRc5z9F3XNw)
* вместо четвертой лекции можно посмотреть [запись лекции 2021.01.22](https://youtu.be/zj-1-invsGM)
* вместо пятой лекции можно посмотреть [запись лекции 2021.01.27](https://www.youtube.com/watch?v=2YRAdMLT4N0&list=PL_HB2SrKjmMJ-dUBtXUSQBZxRftJJX5uL&index=5)
* вместо шестой лекции можно посмотреть [запись лекции 2021.01.29](https://www.youtube.com/watch?v=FA-_Qbpmb6s&list=PL_HB2SrKjmMJ-dUBtXUSQBZxRftJJX5uL&index=6)
* вместо седьмой лекции можно посмотреть [запись лекции 2021.02.03](https://youtu.be/DkNnGeJT2K0)
* вместо восьмой лекции можно посмотреть [запись лекции 2021.02.05](https://youtu.be/c2mej30JnRM)
* вместо девятой лекции можно посмотреть [запись лекции 2021.02.10](https://youtu.be/9ltNRMQmt0U)
* вместо десятой лекции можно посмотреть [запись лекции 2021.02.12](https://youtu.be/zCG_edAziVk)
* вместо одиннадцатой лекции можно посмотреть [запись лекции 2021.02.19](https://youtu.be/6bERf7DMvfg)
* вместо двеннадцатой лекции можно посмотреть [запись лекции 2021.02.24](https://youtu.be/I80UaVOmpxY)
* вместо треннадцатой и четырнадцатых лекций смотреть нечего, так как курс пошел в новый неизведанный виток [введения в MCMC](https://agricolamz.github.io/2022_da4l/%D0%B2%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-%D0%BC%D0%B0%D1%80%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B5-%D1%86%D0%B5%D0%BF%D0%B8-%D0%BC%D0%BE%D0%BD%D1%82%D0%B5-%D0%BA%D0%B0%D1%80%D0%BB%D0%BE.html)


## Используемые пакеты

```{r}
packageVersion("tidyverse")
packageVersion("fitdistrplus")
packageVersion("mixtools")
packageVersion("lme4")
packageVersion("lmerTest")
packageVersion("car")
packageVersion("pscl")
packageVersion("nnet")
packageVersion("MASS")
```

## Домашние задания

* домашнее задание к лекции 24.01.2022:
    * вспомните пожалуйста, условные вероятности, формулу Байеса и при каких условиях ее применяют;
    * посмотрите освежающие материалы про [условную вероятность](http://setosa.io/conditional/) и [формулу Байеса](https://www.youtube.com/watch?v=HZGCoVF3YvM).
* [домашнее задание 1. (дедлайны: 31.01.2022, 07.02.2022)](https://classroom.github.com/a/eJ-3OpbZ)